name: Deploy Backend

on:
  pull_request:
    branches:
      - main  # Ajusta esto según tu rama principal

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta según la versión de Node.js que uses
          cache: 'npm'
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Ejecutar tests
        run: npm test
      
      - name: Generar build
        run: npm run build
      
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" | tr -d '\r' > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private_key.pem
          
      - name: Desplegar en EC2
        run: |
          ssh -v -i ~/.ssh/private_key.pem \
            -o StrictHostKeyChecking=accept-new \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash /app/deploy.sh' 