name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed  # Only triggers when a PR is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

      - name: Test SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}