name: Deploy Backend

on:
  pull_request:
    branches:
      - main  # Ajusta esto según tu rama principal

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajusta según la versión de Node.js que uses
          cache: 'npm'
      
      - name: Instalar dependencias
        run: npm ci
      
      - name: Ejecutar tests
        run: npm test
      
      - name: Generar build
        run: npm run build
      
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Desplegar en EC2
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/app/
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash /app/deploy.sh' 